name: Greetings

on: workflow_dispatch

jobs:
  get-version:
    name: Get image version
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0

    - name: Get Image Version
#      uses: mvktsk/github-actions/get-image-version@master
      uses: VirtoCommerce/vc-github-actions/get-image-tag@master
      id: image

    - name: Show version
      shell: pwsh
      run: |
        Write-Output ${{ steps.image.outputs.tag }}
#        Write-Output ${{ steps.image.outputs.fullVersion }}

